### ISSUE TITLE
perfect FunctionScanner class 

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-code#1]
- [x] Add FunctionScanner for the new feature.
- [x] Add tests for the new feature.
- [x] Add a `CHANGELOG.md` entry for the new feature.

---

Originally posted by @pifeifei at https://github.com/zendframework/zend-code/pull/181

**Comment by weierophinney** [comment]
Hey, all the scanners are generally to be avoided: consider using (and contributing to) `roave/better-reflection` instead

---

Originally posted by @Ocramius at https://github.com/zendframework/zend-code/pull/181#issuecomment-569421249

**Comment by weierophinney** [comment]
# Performance, which can be ignored temporarily

## purpose

The code prompt file is generated automatically according to the [ide-helper-generator](https://github.com/pifeifei/ide-helper-generator) I wrote. It's useful here to scanner



## conceive

> For PHP Extensions, such as `swoole` updates

### Existing ide helper (v2.2.0)

```php
<?php
    
/**
 * docblock and other
 */
class Server{
    /**
     * docblock and other
     * @param string $ip
     * @param int $port
     */
    public function __constuct($ip, $port);
}

/**
 * function docblock and other
 * @param string $ip
 * @param int $port
 */
function swoole_server($ip, $port);
```

### Need to update to 4.x.x

> function and class updating.

```php
<?php
Swoole\Server::__construct(string $host, int $port = 0, int $mode = SWOOLE_PROCESS,$sock_type = SWOOLE_SOCK_TCP);
function swoole_server($ip, $port, $mode, $sock_type);
```

### Desired result

> Version updates inevitably have `functions` / `class` added, deprecated, deprecated, and existing comments combined to generate the latest version of `ide-helper`

```php
<?php
    
/**
 * docblock and other
 */
class Server{
    /**
     * docblock and other
     * @param string $ip
     * @param int $port
     * Some parameters are not, and need to be processed manually.
     */
    public function __constuct(
        string $host, 
        int $port = 0,
        int $mode = SWOOLE_PROCESS,
        $sock_type = SWOOLE_SOCK_TCP
    );
}

/**
 * function docblock and other
 * @param string $ip
 * @param int $port
 */
function swoole_server($ip, $port, $mode, $sock_type);
```

Here you need to use  classScanner and  FunctionScanner.



## The actual situation

One day I need to use `ftp` to update the` html` files of different servers, because the server has an intranet `IP`, using the passive mode, the upload fails all the time, and various searches on the Internet have not found a suitable one. I didn't find it, and finally found [php bug # 55651](https://bugs.php.net/bug.php?id=55651). I need a parameter `FTP_USEPASVADDRESS` to solve the problem instantly. Then I went through the documentation and finally found this parameter in the English page.



Chinese Version：[no `FTP_USEPASVADDRESS`](https://www.php.net/manual/zh/ftp.constants.php#constant.ftp-usepasvaddress)

English original：[Have `FTP_USEPASVADDRESS`](https://www.php.net/manual/en/ftp.constants.php#constant.ftp-usepasvaddress)

If you have the latest code prompt, type `FTP_` and you will be prompted accordingly. There is no need to work hard to find a solution.

Of course, this is official and there is help documentation, so using your own development php extension, or niche php extension, ide-helper automatic generation will be very convenient. You don't need to check the git log to improve the document, although I will not develop PHP at this time. Expansion.



> Conclusion: I have a limited level of English, and I am learning English in order to see the original English documents. These are also translated with Google. Please forgive me if there are errors.

---

Originally posted by @pifeifei at https://github.com/zendframework/zend-code/pull/181#issuecomment-569468145

**Comment by weierophinney** [comment]
The `FunctionGenerator` class is also added to see if it is needed.
at master branch: https://github.com/pifeifei/zend-code.git

---

Originally posted by @pifeifei at https://github.com/zendframework/zend-code/pull/181#issuecomment-569918548

**Comment by Ocramius** [comment]
No longer needed as per #58
