### ISSUE TITLE
laminas-code is not installable on PHP 8.1

### ISSUE THREAD

**Issue by fabianbadoi** [laminas/laminas-code#116]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes (maybe?)
| RFC         | no
| BC Break    | no

#### Summary

PHP 8.1 was release on Nov 25th. Currently, it's not possible to install this library without using `--ignore-platform-reqs`.

From my tests on our code base it looks like everything works fine, I would like to ask you to tag a new version (4.4.4?) with PHP 8.2 included in the version range in `composer.json`.

You already have this change in your (untagged) 4.5.x branch, which I see still needs some PRs merged.

```php
    "require": {
        "php": ">=7.4, <8.2"
    },
```

I can see you delibaretly chose to limit the supported version to `~8.0.0` in your 4.4.x branch. I'm not sure why, but there can be very good reasons for this.

If the main reason is that when you say you support a PHP version, then you actually want to support and make use of the features it brings. This is a high standard to have, and is probably the reason why `laminas-code` is depended on by so many projects.

This also means a lot of people can't migrate to 8.1 because this library. Maybe having the library installable on 8.1 does not mean you actively support 8.1 features yet.

**Comment by akalineskou** [comment]
Having the same issue!

**Comment by garciasdos** [comment]
Same here. Hope this changes soon 🤞🏼

**Comment by alshenetsky** [comment]
Dockerhub has pushed 8.1 tag a few hours ago. Not being able to install **doctrine/migrations** is the main reason why this thread will explode with the impatient developers :)

**Comment by fabianbadoi** [comment]
Impatient, but still very grateful for the effort put into this project! :)

**Comment by akalineskou** [comment]
FWIW I added `"laminas/laminas-code": "4.5.x-dev"` to my composer json to see if anything will break, and all my tests passed on 8.1 (symfony application).

**Comment by alshenetsky** [comment]
@akalineskou Maybe you haven't had time to start using enums or other features from 8.1? I think it's important to the maintainer of this project that these features work, not break.

**Comment by akalineskou** [comment]
@alshenetsky I'm not using this library directly, would me using new 8.1 features in my app have any issues with this library not supporting them?

**Comment by alshenetsky** [comment]
@akalineskou I mean passing tests in your app does not indicate that laminas-code 4.5 can be released sooner. Sure enough that you using this library indirectly via doctrine/migrations or something, that should generate proxy classes. And such generation may break up in case of enums/other 8.1 features (which is you probably don't use yet). I don't know, I am just reasoning with you.

Let's just wait, I can see that development is going on actively.

**Comment by fabianbadoi** [comment]
IMHO, laminas-code 4.5 should support enums and other 8.1 features.

Version 4.4.4 should be installable on PHP 8.1, and runnable (it is). I'm OK with laminas generating php 8.0 code while running on 8.1, if that means I can migrate sooner.

**Comment by Ocramius** [comment]
See https://github.com/laminas/laminas-code/milestone/19

If Laminas is to generate symbols from a reflector, then it must run against PHP 8.1 (currently doesn't generate valid code).

As for the dependency range declaring `~8.0.0`, it is intentional, and even moreso in this package, because even slight additions to the `ext-reflection` API represent a BC break. The next release branch also declares `~8.0.0 || ~8.1.0`, and categorically excludes `8.2.0`.

For the moment being, if you really cannot wait to install all your dependencies against `php:8.1.0`, run `composer update --ignore-platform-req=php`, and take your own responsibility in running a potentially broken dependency graph, as a conscious decision.

Closing here meanwhile.
