### ISSUE TITLE
Error creating API Tools project from composer 

### ISSUE THREAD

**Issue by gildonei** [laminas/laminas-code#126]
### Bug Report

|    Software        |  Version
|------------ | ------
| Windows     | 11 - Full Updated
| PHP CLI | 7.4.9

#### Summary

Trying to create a new empty project according project tutorial in https://api-tools.getlaminas.org/

#### Current behavior

```
composer create-project laminas-api-tools/api-tools-skeleton
....

> php -r 'if (file_exists("src/remove-package-artifacts.php")) include "src/remove-package-artifacts.php";'
Script php -r 'if (file_exists("src/remove-package-artifacts.php")) include "src/remove-package-artifacts.php";' handling the post-create-project-cmd event returned with error code 1
```

#### How to reproduce

In console run `composer create-project laminas-api-tools/api-tools-skeleton`, and use production config files

#### Expected behavior

Create a new project without errors

**Comment by Ocramius** [comment]
This is not related to `laminas/laminas-code` - please report it on https://github.com/laminas-api-tools/api-tools-skeleton

We'd also need more output, specifically what errors occurred (exit code `1` is not sufficient)
