### ISSUE TITLE
Run maganto with PHP 8.1

### ISSUE THREAD

**Issue by Sanjay-100** [laminas/laminas-code#127]
magneto 2.4 with PHP version of 8.1

need to add with php latest version compostable 
  Problem 1
    - Root composer.json requires laminas/laminas-code ^3.5.1 -> satisfiable by laminas/laminas-code[3.5.1].
    - laminas/laminas-code 3.5.1 requires php ^7.3 || ~8.0.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 2
    - Root composer.json requires laminas/laminas-escaper 2.7.0 -> satisfiable by laminas/laminas-escaper[2.7.0].
    - laminas/laminas-escaper 2.7.0 requires php ^7.3 || ~8.0.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 3
    - Root composer.json requires magento/composer 1.6.0 -> satisfiable by magento/composer[1.6.0].
    - magento/composer 1.6.0 requires php ~7.3.0||~7.4.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 4
    - Root composer.json requires pelago/emogrifier ^5.0.0 -> satisfiable by pelago/emogrifier[v5.0.0, v5.0.1].
    - pelago/emogrifier[v5.0.0, ..., v5.0.1] require php ~7.1.0 || ~7.2.0 || ~7.3.0 || ~7.4.0 || ~8.0.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 5
    - laminas/laminas-feed[2.13.0, ..., 2.14.1] require php ^7.3 || ~8.0.0 -> your php version (8.1.1) does not satisfy that requirement.
    - laminas/laminas-feed[2.15.0, ..., 2.16.0] require laminas/laminas-escaper ^2.9 -> found laminas/laminas-escaper[2.9.0] but it conflicts with your root composer.json require (2.7.0).
    - Root composer.json requires laminas/laminas-feed ^2.13.0 -> satisfiable by laminas/laminas-feed[2.13.0, ..., 2.16.0].

**Comment by Ocramius** [comment]
We already support PHP 8.1 on newer releases of `laminas/laminas-code`: it's up to Magento to upgrade here.
