### ISSUE TITLE
Undefined method FileGenerator::fromReflectedFilePath()

### ISSUE THREAD

**Issue by flavioheleno** [laminas/laminas-code#129]
### Bug Report

Method `fromReflectedFilePath` is missing from `Laminas\Code\Generator\FileGenerator`.

|    Q        |   A
|------------ | ------
| Version(s)  | 4.5.1

#### Summary

The documentation refers to `fromReflectedFilePath` static method for [Laminas\Code\Generator\FileGenerator](https://docs.laminas.dev/laminas-code/generator/reference/#laminascodegeneratorfilegenerator), as can be seen in the link.

But once one inspects the code for the aforementioned class, there is no such method. There is no such method for its parent class `AbstractGenerator` either.

Am I missing something?

#### Current behavior

Method `fromReflectedFilePath` is missing from `Laminas\Code\Generator\FileGenerator` although being present in the documentation.

#### How to reproduce

Seems quite straight forward to reproduce.

#### Expected behavior

Method `fromReflectedFilePath` is found in `Laminas\Code\Generator\FileGenerator` **or** is removed from documentation.

**Comment by Ocramius** [comment]
I think it should be removed from the docs: file scanners have completely gone from `laminas/laminas-code`, so some updating is necessary.

Can you send a patch, please?

**Comment by flavioheleno** [comment]
Done @Ocramius, thank you for replying to the issue this fast, very much appreciated.
