### ISSUE TITLE
Unable to use with magento 2.4.4 and PHP 8.1

### ISSUE THREAD

**Issue by zhartaunik** [laminas/laminas-code#131]
### Bug Report

Unable to use with Magento 2.4.4 and PHP 8.1

#### Summary

Try to composer require and you will face incompatibility.

#### How to reproduce

composer require bitexpert/phpstan-magento

  Problem 1
    - laminas/laminas-code[3.3.0, ..., 3.4.1] require php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
    **- laminas/laminas-code[3.5.0, ..., 3.5.1] require php ^7.3 || ~8.0.0 -> your php version (8.1.1) does not satisfy that requirement.**
    - bitexpert/phpstan-magento v0.17.0 requires laminas/laminas-code ~3.3.0 || ~3.4.1 || ~3.5.1 -> satisfiable by laminas/laminas-code[3.3.0, ..., 3.5.1].
    - Root composer.json requires bitexpert/phpstan-magento ^0.17 -> satisfiable by bitexpert/phpstan-magento[v0.17.0].

#### Expected behavior

You need to use a different version of laminas/laminas-code which supports PHP 8.1

**Comment by Ocramius** [comment]
`laminas/laminas-code:^4` ([december 2020](https://github.com/laminas/laminas-code/releases/tag/4.0.0)) was released ages ago: please contact the friendly folks @bitexpert and coordinate with them to help them upgrade https://github.com/bitExpert/phpstan-magento to `laminas/laminas-code:^4`.

/cc @shochdoerfer

Closing here meanwhile: `3.x` will only receive security fixes, nothing else.

**Comment by zhartaunik** [comment]
I'm sorry, but where is it?
![Screenshot from 2022-04-20 20-04-11](https://user-images.githubusercontent.com/11556652/164284986-5b23b478-f7de-4404-9295-40ed3a468e20.png)

**Comment by zhartaunik** [comment]
Ouch, I'm sorry, I created a bug in a wrong repository :(

**Comment by Ocramius** [comment]
@zhartaunik you opened an issue on `laminas/laminas-code`, which supports PHP 8.1 since https://github.com/laminas/laminas-code/releases/tag/4.5.0

**Comment by Ocramius** [comment]
Happens :)

**Comment by shochdoerfer** [comment]
@zhartaunik subscribe to this issue https://github.com/bitExpert/phpstan-magento/issues/193 to be notified when the next release of bitexpert/phpstan-magento is ready.
