### ISSUE TITLE
Generated method declaration return types are not complaint to PSR12

### ISSUE THREAD

**Issue by stephanlueckl** [laminas/laminas-code#134]
### Bug Report

The Laminas\Code\Generator\MethodGenerator does not generate PSR12 compliant code in case of 
setting the return type of the method signature. 
Currently we need to run phpfix after creating a file with the code generator. Don't think this is necessary.

#### Summary

When you have a return type declaration present, there MUST be one space after the colon followed by the type declaration. The colon and declaration MUST be on the same line as the argument list closing parenthesis with no spaces between the two characters.
Source: https://www.php-fig.org/psr/psr-12/#45-method-and-function-arguments

phpcs raises an error with the PSR12.Functions.ReturnTypeDeclaration rule: There must not be a space before the colon in a return type declaration

#### Current behavior

There is one blank between closing parenthesis and colon of the return type (void)
````
    protected function tearDown() : void
    {
        parent::tearDown();
    }
````

#### How to reproduce

````
$method = new Laminas\Code\Generator\MethodGenerator("tearDown");
$method->setReturnType("void");
$method->setVisibility("protected");
$source = "parent::tearDown();";
$method->setBody($source);
`````

#### Expected behavior

No blank between colon and closing parenthesis
````
    protected function tearDown(): void
    {
        parent::tearDown();
    }
````

**Comment by Ocramius** [comment]
I don't think this library is supposed to generate code that is compliant with any specific CS rule set (other than "runnable PHP"), therefore closing here.

You are still welcome to send a patch that improves compatibility with PSR rulesets, and I will gladly merge it, but it is not a requirement for the design of this component

**Comment by ghostwriter** [comment]
Hey @stephanlueckl 

Removing the space on line 378, before the colon `:`,  should resolve this.

https://github.com/laminas/laminas-code/blob/bef71fce9ddb799f69d8435aa2017508b33d58c0/src/Generator/MethodGenerator.php#L377-L379
