### ISSUE TITLE
E_NOTICE with trait method aliases

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-code#15]
I'm getting `Notice: Undefined offset: 1 in /path/to/vendor/zendframework/zend-code/src/Scanner/ClassScanner.php on line 596` using 3.1.0. It looks like this happens with aliased trait methods:

```php
trait A 
{
    function a() {
        // does something
    }
}

class B 
{
    use A {
        a as b;
    }

    function a() {
        b();
        // do something more
    }
}
```

Stepping through the [code](https://github.com/zendframework/zend-code/blob/master/src/Scanner/ClassScanner.php#L596) it looks like `$alias['original']` does not contain '::', causing the notice. I ran into this using zend-expressive-tooling on an existing project. It doesn't seem to cause anything other than annoyance, but I'm not sure if just adding a check for '::' would hide a deeper problem. Thoughts?

---

Originally posted by @kynx at https://github.com/zendframework/zend-code/issues/104

**Comment by Ocramius** [comment]
No longer needed as per #58

**Comment by kynx** [comment]
Heavens to Betsy! I used to alias trait methods? What was wrong with me?!

Nice cleanup you’re doing @Ocramius 🙂
