### ISSUE TITLE
ClassGenerator syntax error, unexpected token ")"  line 1096

### ISSUE THREAD

**Issue by monkey3d** [laminas/laminas-code#169]
Hi,

Fedora 36 - php 8.0.26 - Symfony 5.4. - laminas/laminas-code 4.8.0 

PHP Parse error:  syntax error, unexpected token ")" in vendor/laminas/laminas-code/src/Generator/ClassGenerator.php on line 1096

Before update laminas-code 4.7.1 => 4.8.0 no error.

thanks

**Comment by froschdesign** [comment]
It looks like you are using an older version of PHP:

https://github.com/laminas/laminas-code/blob/dd19fe8e07cc3f374308565667eecd4958c22106/src/Generator/ClassGenerator.php#L1096

First class callable syntax: 

- https://www.php.net/releases/8.1/en.php#first_class_callable_syntax
- https://www.php.net/manual/functions.first_class_callable_syntax.php

laminas-code requires version 8.1 or 8.2:

https://github.com/laminas/laminas-code/blob/dd19fe8e07cc3f374308565667eecd4958c22106/composer.json#L12

**Comment by Ocramius** [comment]
Closing here: you do indeed need PHP 8.1
