### ISSUE TITLE
Tag parsers fail parsing typed array definition like array<int>

### ISSUE THREAD

**Issue by CodeJosch** [laminas/laminas-code#172]
The parsers regexp silently fail parsing typed array definitions like array<int>. 
This can cause issues with MethodGenerator as then the tags name is unset.

Not sure if this should be filed as a feature request or a bug.

https://github.com/laminas/laminas-code/blob/d6ad2c0cd991e1e84857ca299ae47f8d327372cf/src/Reflection/DocBlock/Tag/ParamTag.php#L32

**Comment by Ocramius** [comment]
Could you raise a bug with a failing test case?

**Comment by CodeJosch** [comment]
Here a simple "testclass" for the param tags

Output is 

> 0: Types=array; Name=; Description=
> 1: Types=string[]; Name=$param2; Description=Test parameter 2

Expected
> 0: Types=array<string, string>; Name=$param1; Description=Test parameter 1
> 1: Types=string[]; Name=$param2; Description=Test parameter 2

```
class Test
{
    public function __invoke()
    {
        $reflector = new ClassReflection(self::class);
        $method = $reflector->getMethod('testMethod');

        foreach ($method->getDocBlock()->getTags('param') as $index => $tag) {
            /** @var ParamTag $tag */
            echo sprintf(
                '%d: Types=%s; Name=%s; Description=%s' . PHP_EOL,
                $index,
                implode('|', $tag->getTypes()),
                $tag->getVariableName(),
                $tag->getDescription()
            );
        }
    }

    /**
     * @param array<string,string> $param1 Test parameter 1
     * @param string[]             $param2 Test parameter 2
     *
     * @return bool
     */
    public function testMethod(array $param1, array $param2): bool
    {
        return true;
    }
}
```

**Comment by Ocramius** [comment]
Oh, I see.

Yeah, sounds like a reasonable limitation though, because tag parsers were written waaaaaaaay before `array<K, V>` became mainstream (~3 years ago?)

I wouldn't call this a bug then, but rather an improvement that needs work.

Potentially worth not even using `laminas/laminas-code` for this, but instead referring to:

 * https://github.com/phpstan/phpdoc-parser
 * https://github.com/phpDocumentor/ReflectionDocBlock

**Comment by CodeJosch** [comment]
Yes thats what I meant by feature request or bug.. But the documentor lib is good for this, so I'll close this issue
