### ISSUE TITLE
Implement generateShortOrCompleteClassname method for MethodGenerator and TypeGenerator 

### ISSUE THREAD

**Issue by simon-mundy** [laminas/laminas-code#176]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

#### Summary

I am using the Code Generator in my CLI to create Controllers and Factories. My CLI tool creates a factory using something like the following:-

```        $factoryClass = $ucName . 'ControllerFactory';
        $controllerClass = ucfirst($module) . '\\Controller\\' . $controller;

        $code = new Generator\ClassGenerator();
        $code->setNamespaceName(ucfirst($module) . '\\Controller\Factory')
             ->addUse($controllerClass)
             ->addUse('Psr\\Container\\ContainerInterface')
             ->addUse('Laminas\\ServiceManager\\Factory\\FactoryInterface');

        $code->setName($factoryClass)
             ->addMethodFromGenerator(
                (new Generator\MethodGenerator(
                    '__invoke',
                    [
                        new Generator\ParameterGenerator('container', '\Psr\\Container\\ContainerInterface'),
                        (new Generator\ParameterGenerator())->setName('requestedName'),
                        (new Generator\ParameterGenerator())->setName('options')->setType('array')->setDefaultValue(null)
                    ],
                    Generator\MethodGenerator::FLAG_PUBLIC,
                    'return new $requestedName();'
                ))->setReturnType($controllerClass),
             )
             ->setImplementedInterfaces([
             	'Laminas\\ServiceManager\\Factory\\FactoryInterface'
             ]);

        $file = new Generator\FileGenerator(
            [
                'classes'  => [$code],
            ]
        );
```

What I'd like to achive is the short-form version of Type hints for parameters and return Types like so:-

```<?php

namespace Application\Controller\Factory;

use Application\Controller\AccommodationController;
use Psr\Container\ContainerInterface;
use Laminas\ServiceManager\Factory\FactoryInterface;

class AccommodationControllerFactory implements FactoryInterface
{
    public function __invoke(ContainerInterface $container, $requestedName, array $options = null): AccommodationController
    {
        return new $requestedName();
    }
}
```

However the current output forces the full path for each of these types:-

```<?php

namespace Application\Controller\Factory;

use Application\Controller\AccommodationController;
use Psr\Container\ContainerInterface;
use Laminas\ServiceManager\Factory\FactoryInterface;

class AccommodationControllerFactory implements FactoryInterface
{
    public function __invoke(\Psr\Container\ContainerInterface $container, $requestedName, array $options = null) : \Application\Controller\AccommodationController
    {
        return new $requestedName();
    }
}
```

Would it be possible to utilise something like the `generateShortOrCompleteClassname()` method from the ClassGenerator which could then pass the current namespace and use aliases to these methods and types to use when determining how to write them?

For BC the classes could continue to behave the way they do now, but if the namespace and aliases were passed in via  `setNamespaceAndUseAlias` method then they could use look to use the short-form version?

## Current usage
```
                (new Generator\MethodGenerator(
                    '__invoke',
                    [
                        new Generator\ParameterGenerator('container', '\Psr\\Container\\ContainerInterface'),
                        (new Generator\ParameterGenerator())->setName('requestedName'),
                        (new Generator\ParameterGenerator())->setName('options')->setType('array')->setDefaultValue(null)
                    ],
                    Generator\MethodGenerator::FLAG_PUBLIC,
                    'return new $requestedName();'
                ))->setReturnType($controllerClass),
```

## Proposes usage
```
                (new Generator\MethodGenerator(
                    '__invoke',
                    [
                        new Generator\ParameterGenerator('container', '\Psr\\Container\\ContainerInterface'),
                        (new Generator\ParameterGenerator())->setName('requestedName'),
                        (new Generator\ParameterGenerator())->setName('options')->setType('array')->setDefaultValue(null)
                    ],
                    Generator\MethodGenerator::FLAG_PUBLIC,
                    'return new $requestedName();'
                ))
                ->setReturnType($controllerClass)
                ->setNamespaceAndUseAlias($classGenerator->getNamespaceName(), $classGenerator->getUses())
```

**Comment by froschdesign** [comment]
@simon-mundy 
> I am using the Code Generator in my CLI to create Controllers and Factories.

Nice! 👍🏻 
I wish we would _eat our own dog food_ also in the CLI commands of components.

> What I'd like to achive is the short-form version of Type hints for parameters and return Types…

My first thought was to use a coding standards fixer. The tool does the work and much more, like sorting of imports, group use declarations or not, etc.

**Comment by Ocramius** [comment]
I'm against starting to generate `use` statements: it opens a massive can of worms.

The problem here is that our generator is also the builder.

If we had a builder object that held definitions, and then a generator that generates FQCN symbols or aliased/imported symbols, I wouldn't be adverse

This library is not in the shape/quality to support that, at this moment: we'd first need to have a central concept where aliases are collected and deduplicated.

I'm happy to introduce something that re-thinks the library at fundamental level, but the generated code is for machine consumption here, not human consumption.

**Comment by simon-mundy** [comment]
@Ocramius I'm not sure I fully understand - I'm not asking to generate `use` statements. The `FileGenerator` class already takes care of that.

I think this component could be equally adept at generating code for machine consumption as much as it could be to help reduce manual tasks from a developer standpoint. 

May I ask why you feel the library is not in the shape to do this?

**Comment by Ocramius** [comment]
I just explained it, but to rephrase: all internal symbols assume FQCN, not relative names.

If we want to do FQCN as well as relative names, we need to make sure that the library internally represents symbols as such too.

Right now, the correct pipeline to generate human-readable code instead is:

 1. run this tool
 2. run your favorite CS fixer tool on top of it

This can be changed, but with very major effort: mixing FQCN and non-FQCN references in the in-memory representation is not viable.
