### ISSUE TITLE
Space after close parenthesis when return type is presen in the method generator

### ISSUE THREAD

**Issue by ngonzalez-so** [laminas/laminas-code#178]
### Bug Report

The method generator is not following the PSR-12 standard that state:

*"When you have a return type declaration present, there MUST be one space after the colon followed by the type declaration. The colon and declaration MUST be on the same line as the argument list closing parenthesis with no spaces between the two characters."*

|    Q        |   A
|------------ | ------
| Version(s)  | 4.10.0

#### Summary

The return type declaration does not match wit the PSR-12 standard.

#### Current behavior

Add an unnecessary extra space between the closing parenthesis and the type declaration.

#### How to reproduce

```
$interfaceGenerator = new \Laminas\Code\Generator\InterfaceGenerator();
$interfaceGenerator->setName('NameInterface');
$methodGenerator = new \Laminas\Code\Generator\MethodGenerator(
    name: 'methodName'
);
$methodGenerator->setReturnType('int');
$interfaceGenerator->addMethodFromGenerator($methodGenerator);
echo $interfaceGenerator->generate();
```

#### Expected behavior

When you have a return type declaration present, there MUST be one space after the colon followed by the type declaration. The colon and declaration MUST be on the same line as the argument list closing parenthesis with no spaces between the two characters.

**Comment by Ocramius** [comment]
Feel free to send a patch, but this code generator is not required to follow any specific coding standard :-)

**Comment by ngonzalez-so** [comment]
> Feel free to send a patch, but this code generator is not required to follow any specific coding standard :-)

Thanks @Ocramius , yes, you're right about that code generator is not required to follow any specific coding standard, but since Laminas is a "standards-based" it would be nice to have... and it's very easy to fix. But thanks anyway.

**Comment by Ocramius** [comment]
I'll gladly accept a patch
