### ISSUE TITLE
Laminas does not support union types  

### ISSUE THREAD

**Issue by evginiys** [laminas/laminas-code#181]
### Bug Report

 Laminas does not support union types  

|    Q        |   A
|------------ | ------
| Magento  | 2.4.5-p2
| PHP  |  8.1
| Laminas | 4.5.0

### Summary
When i use some classes with union type as a parametr 
i got this issue

Call to undefined method ReflectionUnionType::isBuiltin()#0 /Users/ylutsenko/projects/yorknow/vendor/magento/framework/Code/Reader/ArgumentsReader.php(111):  

### How to reproduce

Create class with union parametr as  __constructor(SplFileObject|Stream $doc)

### Expected behavior

No errors during setup:di:compile

**Comment by Ocramius** [comment]
4.5.0 was released forever ago: please upgrade.
