### ISSUE TITLE
TypeGenerator fails with type "null" cannot be nullable

### ISSUE THREAD

**Issue by robertlemke** [laminas/laminas-code#185]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 14.12.x

#### Summary

Consider the following method:

```php
    public function alwaysNull(): null
    {
        return null;
    }
```

When I generate a method using `MethodGenerator::copyMethodSignature()`, the `TypeGenerator` fails with:

> Type "null" cannot be nullable

**Comment by gsteel** [comment]
Closed via #186
