### ISSUE TITLE
Support nullable types

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-code#19]
As per PHP 7.1, it is possible to define nullability of a type by adding a `?` in front of it ( https://wiki.php.net/rfc/nullable_types ).

A few heads-up:
- careful about `?Foo $bar = null` vs `?Foo $bar` vs `Foo $bar = null`
- need to eventually patch the `TypeGenerator` to include the `?` in it (not sure yet)

---

Originally posted by @Ocramius at https://github.com/zendframework/zend-code/issues/85

**Comment by weierophinney** [comment]
Surely resolving the fact that `Zend\Code\Scanner\MethodScanner` doesn't properly handle scalar type declarations should come before supporting nullable types? #56 still hasn't received any acknowledgement.


---

Originally posted by @djmattyg007 at https://github.com/zendframework/zend-code/issues/85#issuecomment-234905005

**Comment by weierophinney** [comment]
@djmattyg007 I reported the issue completely independently from other issues. 


---

Originally posted by @Ocramius at https://github.com/zendframework/zend-code/issues/85#issuecomment-234914308

**Comment by weierophinney** [comment]
My point was that PHP 7.0 compatibility should be targeted before PHP 7.1 compatibility.


---

Originally posted by @djmattyg007 at https://github.com/zendframework/zend-code/issues/85#issuecomment-234973411

**Comment by weierophinney** [comment]
Ah yes, that is because the codegen part of this component is already 7.0 compatible. I hardly ever use the scanner, as it is not AST-based (which makes it very unstable)


---

Originally posted by @Ocramius at https://github.com/zendframework/zend-code/issues/85#issuecomment-235038266

**Comment by weierophinney** [comment]
If no one is maintaining the scanning code, shouldn't it be removed?


---

Originally posted by @djmattyg007 at https://github.com/zendframework/zend-code/issues/85#issuecomment-239420763

**Comment by Ocramius** [comment]
No longer needed as per #58
