### ISSUE TITLE
Type "?array|string|null" is a union type, and therefore cannot be also marked nullable with the "?" prefix

### ISSUE THREAD

**Issue by glo71317** [laminas/laminas-code#193]
### BC Break Report

|    Q        |   A
|------------ | ------
| Version     | 14.12.x
--

<br class="Apple-interchange-newline">

#### Summary
In new version of Symfony/console:6:3.x
https://github.com/symfony/console/blob/6.3/Command/Command.php#L475-L497
string|array $shortcut = null

While generating the class getting below error:
<img width="450" alt="Screenshot 2023-10-03 at 3 19 24 PM" src="https://github.com/laminas/laminas-code/assets/85922880/386b548e-79ed-4231-b5db-545a7f5a072f">
<img width="690" alt="Screenshot 2023-10-03 at 4 10 21 PM" src="https://github.com/laminas/laminas-code/assets/85922880/ca729d27-2221-43b3-867b-29bb1eac20bf">

#### How to reproduce
Steps 1: After updating the symfony/console latest version 6.3.x
Steps 2: Ran the bin/magento di:compile
It is failing at line number 105 - https://github.com/laminas/laminas-code/blob/4.13.x/src/Generator/TypeGenerator.php#L104-L108

After adding temporary fix in same file **line 95 to 97** , I am able to generate all the classes by running bin/magento di:compile
<img width="1012" alt="Screenshot 2023-10-03 at 7 58 06 PM" src="https://github.com/laminas/laminas-code/assets/85922880/528a7064-f5a4-4db7-a2a0-85af439c4c14">

**Comment by glo71317** [comment]
Hi @omerida,
I raised this issue, still i am working at my end to figure out. As far as i done the analysis and it seems to me some BIC issue is introduced in latest version of symfony/console.
I think it should be resolve at laminas end. Can you help in this regard or suggest?

**Comment by omerida** [comment]
> Hi @omerida, I raised this issue, still i am working at my end to figure out. As far as i done the analysis and it seems to me some BIC issue is introduced in latest version of symfony/console. I think it should be resolve at laminas end. Can you help in this regard or suggest?

sorry - why am I being tagged into this issue?

**Comment by glo71317** [comment]
> > Hi @omerida, I raised this issue, still i am working at my end to figure out. As far as i done the analysis and it seems to me some BIC issue is introduced in latest version of symfony/console. I think it should be resolve at laminas end. Can you help in this regard or suggest?
> 
> sorry - why am I being tagged into this issue?

I tagged you for suggestion, I thought may be you may aware about it if not i will provide the fix for the same

**Comment by Ocramius** [comment]
What's the resolution here? Is there a test case or fix?

**Comment by glo71317** [comment]
We identified the RCA for this issue, So, we had fixed at our end. Thanks

**Comment by Ocramius** [comment]
> we had fixed at our end

So issue does not occur here?
