### ISSUE TITLE
Fix return type of FileGenerator::getClass

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-code#2]
Provide a narrative description of what you are trying to accomplish:

- [Y ] Is this related to quality assurance?
Return type of `\Zend\Code\Generator\FileGenerator::getClass` only has `ClassGenerator` while it can also return false when the classes array is empty.
PHPStan will whine about this, because it should always return a true-thy return, also it gives the perception it will always return the ClassGenerator (while it doesn't always do that)

Therefor I added the false to the return type in the docblock.

---

Originally posted by @janvernieuwe at https://github.com/zendframework/zend-code/pull/177

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
(The mention from the 22nd of December 2023 was added by mistake, so it does not count as real activity)
