### ISSUE TITLE
DirectoryScanner->getClasses() returns no classes

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-code#28]
I scan with this class a directory for classes. But getClasses returns an empty array. When I test getFiles it works I get dozens files. I use php7.

---

Originally posted by @aight8 at https://github.com/zendframework/zend-code/issues/50

**Comment by weierophinney** [comment]
Possibly duplicate of #49. Check if you are running PHP 7.0.5 or 7.0.4


---

Originally posted by @Ocramius at https://github.com/zendframework/zend-code/issues/50#issuecomment-209507474

**Comment by Ocramius** [comment]
No longer needed as per #58
