### ISSUE TITLE
Docblock  for constants is not supported

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-code#29]
Hi,

I think that Classgenerator should support docblock for constants . Ex :

``` php
<?php

namespace Participation\Controller;

class IndexController extends \CS\ZF2\Core\Mvc\Controller\AbstractActionController
{

    /**
     * @var string
     */
    const STEP_CONTACT_OK = 'CONTACT_OK';
```

---

Originally posted by @neilime at https://github.com/zendframework/zend-code/issues/44

**Comment by Ocramius** [comment]
This is generally a problem of constant in the reflection API: not fixable by this library - requires upstream fixes.
