### ISSUE TITLE
Not using return value of array_map in ClassGenerator->setImplementedInterfaces

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-code#3]
https://github.com/zendframework/zend-code/blob/master/src/Generator/ClassGenerator.php#L476-L482 has the following snippet

```php
        array_map(function ($implementedInterface) {
            return (string) TypeGenerator::fromTypeString($implementedInterface);
        }, $implementedInterfaces);

        $this->implementedInterfaces = $implementedInterfaces;
```

That's a no-op, since the return value of the array_map isn't used. I think that the array_map should be removed, replaced with array_walk (probably pointless unless it would throw), or (probably) be changed to:

```php
        $this->implementedInterfaces = array_map(function ($implementedInterface) {
            return (string) TypeGenerator::fromTypeString($implementedInterface);
        }, $implementedInterfaces);
```

The latter seems likely given the rest of the changes in https://github.com/zendframework/zend-code/commit/ec09875ecc89347a6109e0eaea4a75e4d54dd8c3

This was detected via static analysis, I'm not sure of the impact of fixing this.

http://php.net/array_map

---

Originally posted by @TysonAndre at https://github.com/zendframework/zend-code/issues/165

**Comment by Ocramius** [comment]
This is correct: that filter is not supposed to use the returned value, but just to check that the input is somewhat used.

Should've been an `array_walk()`, but closing here, as in #57 I documented it briefly, and we can further improve it when moving to aggressive `vimeo/psalm` analysis.
