### ISSUE TITLE
Property without default value

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-code#34]
Is it possible to generate property without default value?

``` php
$x = new ClassGenerator;
        $x->setName('Classa');
        $x->addProperty('test');
```

Should output:

``` php
class Classa {
public $test;
}
```

Maybe there should be new type

``` php
TYPE_OMIT
```

---

Originally posted by @wwwgo-pl at https://github.com/zendframework/zend-code/issues/28

**Comment by vrkansagara** [comment]
is there any update on this ?

**Comment by vrkansagara** [comment]
@michalbundyra  You can close this issue as I am sharing code for the user.

~~~php
$propertiesGenerator = new Laminas\Code\Generator\PropertyGenerator();
$propertiesGenerator->omitDefaultValue(true);
$propertiesGenerator->setName('test');

$class = new Laminas\Code\Generator\ClassGenerator();
$class->addProperties($propertiesGenerator);
~~~

Ping :-  @wwwgo-pl

**Comment by Ocramius** [comment]
Thanks for verifying this, @vrkansagara!
