### ISSUE TITLE
`ParameterGenerator` always fails with variadic parameters

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-code#35]
The `ParameterGenerator` always considers [`ReflectionParameter#isOptional()`](https://github.com/zendframework/zend-code/blob/3da502f243df7a189b9c1cfc70a96944ef111957/src/Generator/ParameterGenerator.php#L77) when checking for default parameter values.

A variadic argument is, though, always optional and never has a default value.

---

Originally posted by @Ocramius at https://github.com/zendframework/zend-code/issues/6

**Comment by mchekin** [comment]
@michalbundyra 
I would like to take care of this issue.

**Comment by mchekin** [comment]
@michalbundyra 

Maybe I do not understand the issue, but according to the source code:
https://github.com/laminas/laminas-code/blob/4.1.x/src/Generator/ParameterGenerator.php#L59-L65

And according to the tests:
https://github.com/laminas/laminas-code/blob/4.1.x/test/Generator/ParameterGeneratorTest.php#L506-L556

It seems like everything works as expected.

Am I missing something here?

**Comment by Ocramius** [comment]
@mchekin the test checks `->isVariadic()`, but not `->isOptional()`, I think?

**Comment by mchekin** [comment]
@Ocramius 
@michalbundyra 

I created a pull request which prevents generating variadic parameters with default value + an accompanying unit test https://github.com/laminas/laminas-code/pull/72

**Comment by Ocramius** [comment]
Handled in #72
