### ISSUE TITLE
This package should not "replace" zend/code

### ISSUE THREAD

**Issue by BenMorel** [laminas/laminas-code#37]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.4.1

#### Summary

This package is marked as **replacing** `zendframework/zend-code`:

https://github.com/laminas/laminas-code/blob/8499ce005b4c028af6c9e6145a27b6ea5d3c716b/composer.json#L67-L69

There seems to be a misunderstanding in what `replace` [actually does](https://getcomposer.org/doc/04-schema.md#replace): the package must be 100% compatible with the replaced one, which is obviously not the case here.

As it stands, this breaks composer installations and throws class not found errors.

Sure, you can install the `laminas/laminas-zendframework-bridge`, but composer doesn't do that automatically.

#### Current behavior

> Class 'Zend\Code\Generator\ClassGenerator' not found

#### How to reproduce

Install `ocramius/proxy-manager` on PHP 7.3; try to use it.

**Comment by BenMorel** [comment]
Sorry, I just realized that this package does require `laminas/laminas-zendframework-bridge`, so there is no bug here.

There is, however, an issue with composer autoloading I think:

- by default, in `--no-dev` mode, the Class not found error occurs:
    ```
    $ composer install --no-dev
    $ bin/console doctrine:migrations:migrate prev -n
    ```
    > Migration 035 failed during Pre-Checks. Error Class 'Zend\Code\Generator\ClassGenerator' not found
- if I manually require `laminas/laminas-zendframework-bridge`, it now works:
    ```
    $ composer require laminas/laminas-zendframework-bridge
    $ composer install --no-dev
    $ bin/console doctrine:migrations:migrate prev -n
    ```
    > Migrating down to 034 from 035
    > (...)

Even though diffing `composer.lock` shows no changes, apart from the `content-hash`, manually requiring the bridge fixes the issue.

Is this a bug with composer, should I file a bug there?

**Comment by BenMorel** [comment]
Looks like I somehow ended up with a broken composer config. Here's how I fixed it:

```
rm -rf vendor
rm -f composer.lock
rm -f symfony.lock
composer update
composer install --no-dev
```

Tell me why, but `laminas/laminas-code` was now replaced with `zendframework/zend-code`, and the problem is gone for me.

I believe there's a bug somehow with composer, but I wasn't able to make a reproducible test case after more than one hour, so I'm giving up now.

Maybe the steps above will help someone with the same issue I encountered.

**Comment by magnetik** [comment]
I had the same problem. I suspect symfony flex to have messed with the dependencies. 

IMO the bug should be open as I think you are right about the fact that this package is NOT a "replace"(ment) of zend-code.

**Comment by BenMorel** [comment]
@magnetik IDK, because it requires the bridge, it effectively replaces zend-code, with no modification required on code using the library.

**Comment by Xerkus** [comment]
@magnetik are you using latest composer version?

**Comment by magnetik** [comment]
I'm running 1.9.2

**Comment by magnetik** [comment]
Hum but maybe that's someone on my team that was using 1.8.6 that did the composer update. Could this be it?

**Comment by crmpicco** [comment]
> Looks like I somehow ended up with a broken composer config. Here's how I fixed it:
> 
> ```
> rm -rf vendor
> rm -f composer.lock
> rm -f symfony.lock
> composer update
> composer install --no-dev
> ```
> 
> Tell me why, but `laminas/laminas-code` was now replaced with `zendframework/zend-code`, and the problem is gone for me.
> 
> I believe there's a bug somehow with composer, but I wasn't able to make a reproducible test case after more than one hour, so I'm giving up now.
> 
> Maybe the steps above will help someone with the same issue I encountered.

Thanks a bunch for this comment. This is exactly what I had to do.

**Comment by Xerkus** [comment]
There is some kind of issue here that looks more of a support kind rather than a bug.
Please take it to our [discourse forums](https://discourse.laminas.dev/c/questions/components) so we can figure it out and help you.

**Comment by BenMorel** [comment]
@Xerkus Indeed, I don't think there's any issue with laminas-code.
This is more likely a Composer bug. Closing.

**Comment by remorhaz** [comment]
Probably this one I've just discovered. If yes then temporary workaround is just not to use `--no-dev` key.

https://github.com/composer/composer/issues/8622
