### ISSUE TITLE
Return type self is not an internal type while code generation

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-code#4]
Is it right behavior that TypeGenerator does not think self type is an internal type?
Because of that my code generation causes wrong return type in resulting file.
`public function foo(): self`
turns on 
`public function foo(): \self`
It thinks self is a class.
Zend\Code\Generator\TypeGenerator:36
`private static $internalPhpTypes = ['void', 'int', 'float', 'string', 'bool', 'array', 'callable', 'iterable'];`

---

Originally posted by @mastiuhin-olexandr at https://github.com/zendframework/zend-code/issues/161

**Comment by weierophinney** [comment]
@mastiuhin-olexandr `self` is an alias for "this class". Passing `self` to the `TypeGenerator` is incorrect, as `self` has no meaning without its surrounding context.

I'd rather say that it should be rejected completely, and an exception should be thrown.

---

Originally posted by @Ocramius at https://github.com/zendframework/zend-code/issues/161#issuecomment-429856131

**Comment by Ocramius** [comment]
Closing as per previous comment - the behavior is indeed correct.
