### ISSUE TITLE
addConstant() is producing code with keyword `public`

### ISSUE THREAD

**Issue by divix1988** [laminas/laminas-code#40]
`addConstant()` method is outputting with invalid output:
```
public const ELEMENT_PROPERTY1 = 'property1';
```
(notice the `public` keyword)

**DETAILS:**
`PropertyGenerator.php` line: 232, we need to drop `$this->getVisibility()`

**Comment by weierophinney** [comment]
Dropping a note so that people searching for this scenario and finding this issue understand why it was closed.

Starting with PHP 7.1, PHP allows declaring visibility on constants. Current versions of this library target 7.1 and up.
