### ISSUE TITLE
Method body extract error with express static::class

### ISSUE THREAD

**Issue by wenbinye** [laminas/laminas-code#44]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.4.1

#### Summary

```php
class Foo
{
    public static function test() {
        return static::class;
    }
}

$class = \Laminas\Code\Generator\ClassGenerator::fromReflection(
    new \Laminas\Code\Reflection\ClassReflection(Foo::class));
echo $class->generate();
```
The `test` method body was not extract successfully. 

#### Current behavior

Output code is :

```php
class Foo
{

    public static function test()
    {
        return
    }


}
```

#### Expected behavior

```php
class Foo
{

    public static function test()
    {
        return static:class;
    }


}

```

**Comment by Ocramius** [comment]
Probably related to code scanners, which are to deprecated and to be
removed.

Consider using Roave/better-reflection if you need to manipulate AST
