### ISSUE TITLE
Verify `4.0.x` branch against real-world applications before releasing

### ISSUE THREAD

**Issue by Ocramius** [laminas/laminas-code#64]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | no
| RFC         | yes
| BC Break    | no

#### Summary

Before releasing to `4.0.x`, we need to first test this in the wild with newer PHP 8.0 features.

Most notably, @Ocramius specifically will integrate the component with [`ocramius/proxy-manager`](https://github.com/Ocramius/ProxyManager/) before calling it "ready for 8.0", due to downstream CI pipeline being extremely strict.

**Comment by martinssipenko** [comment]
I tried using `laminas/laminas-code` `4.x` branch with `ocramius/proxy-manager`.

Using `ocramius/proxy-manager:2.11.x` as base:
https://github.com/Ocramius/ProxyManager/pull/637

Using [8.0 patch](https://github.com/Ocramius/ProxyManager/pull/628) as base:
https://github.com/Ocramius/ProxyManager/pull/639

Also tried using 4.x on `laminas-server`:
https://github.com/laminas/laminas-server/pull/21

**Comment by martinssipenko** [comment]
Is this enough for 4.0 release or is there anything else I could do?

**Comment by Ocramius** [comment]
Tested this carefully - works as expected, so :ship:
