### ISSUE TITLE
PropertyGenerator::fromReflection throws E_NOTICE for non-default typed properties

### ISSUE THREAD

**Issue by rieschl** [laminas/laminas-code#76]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 4.2.0

Apparently, `\ReflectionClass::getDefaultProperties` doesn't return typed properties without a default value, thus an `E_NOTICE` is emitted when assigning [`$defaultValue`](https://github.com/laminas/laminas-code/blob/4.3.x/src/Generator/PropertyGenerator.php#L38) because it's trying to access an undefined index.

**Comment by Ocramius** [comment]
Handled in #77
