### ISSUE TITLE
Compile error type on MethodGenerator.php line 25 using php 8.0

### ISSUE THREAD

**Issue by edurk89** [laminas/laminas-code#79]
Using php 8.0 with symfony in my case, I could see the following bug while container is building:

`"laminas/laminas-code": "4.2.1"`

`Type of Laminas\Code\Generator\MethodGenerator::$docBlock must be ?Laminas\Code\Generator\DocBlockGenerator (as in class Laminas\Code\Generator\AbstractMemberGenerator) in /app/vendor/laminas/laminas-code/src/Generator/MethodGenerator.php on line 25`

It seems that the property `protected ?DocBlockGenerator $docBlock = null` due an error type.

I've tried to remove type hint DocBlockGenerator to do a test and it works.

Your package is automatically added when syfony/orm-pack is installed, but this bug makes an error and don't allow to use it.

**Comment by Ocramius** [comment]
What is the full stack trace?

**Comment by edurk89** [comment]
`Symfony\Component\ErrorHandler\Error\FatalError:
Compile Error: Type of Laminas\Code\Generator\MethodGenerator::$docBlock must be ?Laminas\Code\Generator\DocBlockGenerator (as in class Laminas\Code\Generator\AbstractMemberGenerator)

  at /app/vendor/laminas/laminas-code/src/Generator/MethodGenerator.php:25   `

**Comment by Ocramius** [comment]
That's only one line: what's the full trace, so we can see what is causing the problem?

Overall, the type is already the one suggested by the exception.

**Comment by AlexGx** [comment]
We have same issue on 8.0.0, on 8.0.3 works fine.

**Comment by Ocramius** [comment]
I suppose this is a bug on PHP then? Any reference to an upstream related
issue?

**Comment by edurk89** [comment]
`Fatal error: Type of Laminas\Code\Generator\MethodGenerator::$docBlock must be ?Laminas\Code\Generator\DocBlockGenerator (as in class Laminas\Code\Generator\AbstractMemberGenerator) in /app/vendor/laminas/laminas-code/src/Generator/MethodGenerator.php on line 25

Call Stack:
    0.0136     349768   1. {main}() /app/bin/console:0
    0.0307     680448   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /app/bin/console:43
    0.0337     780384   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /app/vendor/symfony/console/Application.php:166
    0.0337     780384   4. Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() /app/vendor/symfony/framework-bundle/Console/Application.php:74
    0.0337     780384   5. App\Kernel->boot() /app/vendor/symfony/framework-bundle/Console/Application.php:168
    0.0337     780384   6. App\Kernel->preBoot() /app/vendor/symfony/http-kernel/Kernel.php:121
    0.0400    1016592   7. App\Kernel->initializeContainer() /app/vendor/symfony/http-kernel/Kernel.php:780
    0.3372    6841000   8. App\Kernel->dumpContainer() /app/vendor/symfony/http-kernel/Kernel.php:551
    0.3403    6917544   9. Symfony\Component\DependencyInjection\Dumper\PhpDumper->dump() /app/vendor/symfony/http-kernel/Kernel.php:728
    0.4585    9803192  10. Symfony\Component\DependencyInjection\Dumper\PhpDumper->generateProxyClasses() /app/vendor/symfony/dependency-injection/Dumper/PhpDumper.php:228
    0.4586    9824136  11. Symfony\Bridge\ProxyManager\LazyProxy\PhpDumper\ProxyDumper->getProxyCode() /app/vendor/symfony/dependency-injection/Dumper/PhpDumper.php:569
    0.4586    9824136  12. Symfony\Bridge\ProxyManager\LazyProxy\PhpDumper\ProxyDumper->generateProxyClass() /app/vendor/symfony/proxy-manager-bridge/LazyProxy/PhpDumper/ProxyDumper.php:82
    0.4591    9830392  13. Symfony\Bridge\ProxyManager\LazyProxy\PhpDumper\LazyLoadingValueHolderGenerator->generate() /app/vendor/symfony/proxy-manager-bridge/LazyProxy/PhpDumper/ProxyDumper.php:104
    0.4591    9830392  14. Symfony\Bridge\ProxyManager\LazyProxy\PhpDumper\LazyLoadingValueHolderGenerator->generate() /app/vendor/symfony/proxy-manager-bridge/LazyProxy/PhpDumper/LazyLoadingValueHolderGenerator.php:28
    0.4626    9968536  15. array_map() /app/vendor/friendsofphp/proxy-manager-lts/src/ProxyManager/ProxyGenerator/LazyLoadingValueHolderGenerator.php:98
    0.4626    9971152  16. ProxyManager\ProxyGenerator\LazyLoadingValueHolderGenerator::ProxyManager\ProxyGenerator\{closure:/app/vendor/friendsofphp/proxy-manager-lts/src/ProxyManager/ProxyGenerator/LazyLoadingValueHolderGenerator.php:126-150}() /app/vendor/friendsofphp/proxy-manager-lts/src/ProxyManager/ProxyGenerator/LazyLoadingValueHolderGenerator.php:98
    0.4626    9971152  17. Symfony\Component\ErrorHandler\DebugClassLoader->loadClass() /app/vendor/friendsofphp/proxy-manager-lts/src/ProxyManager/ProxyGenerator/LazyLoadingValueHolderGenerator.php:128
    0.4627    9971936  18. include('/app/vendor/friendsofphp/proxy-manager-lts/src/ProxyManager/ProxyGenerator/LazyLoadingValueHolder/MethodGenerator/LazyLoadingMethodInterceptor.php') /app/vendor/symfony/error-handler/DebugClassLoader.php:346
    0.4627    9971936  19. Symfony\Component\ErrorHandler\DebugClassLoader->loadClass() /app/vendor/friendsofphp/proxy-manager-lts/src/ProxyManager/ProxyGenerator/LazyLoadingValueHolder/MethodGenerator/LazyLoadingMethodInterceptor.php:19
    0.4628    9972656  20. include('/app/vendor/friendsofphp/proxy-manager-lts/src/ProxyManager/Generator/MethodGenerator.php') /app/vendor/symfony/error-handler/DebugClassLoader.php:346
    0.4628    9972656  21. Symfony\Component\ErrorHandler\DebugClassLoader->loadClass() /app/vendor/friendsofphp/proxy-manager-lts/src/ProxyManager/Generator/MethodGenerator.php:14
    0.4628    9972656  22. Laminas\ZendFrameworkBridge\Autoloader::Laminas\ZendFrameworkBridge\{closure:/app/vendor/laminas/laminas-zendframework-bridge/src/Autoloader.php:93-121}() /app/vendor/symfony/error-handler/DebugClassLoader.php:350
    0.4628    9973216  23. Composer\Autoload\ClassLoader->loadClass() /app/vendor/laminas/laminas-zendframework-bridge/src/Autoloader.php:112
    0.4628    9973216  24. Composer\Autoload\includeFile() /app/vendor/composer/ClassLoader.php:346
    0.4630    9974632  25. include('/app/vendor/laminas/laminas-code/src/Generator/MethodGenerator.php') /app/vendor/composer/ClassLoader.php:478

Symfony\Component\ErrorHandler\Error\FatalError^ {#5136
  -error: array:4 [
    "type" => 64
    "message" => "Type of Laminas\Code\Generator\MethodGenerator::$docBlock must be ?Laminas\Code\Generator\DocBlockGenerator (as in class Laminas\Code\Generator\AbstractMemberGenerator)"
    "file" => "/app/vendor/laminas/laminas-code/src/Generator/MethodGenerator.php"
    "line" => 25
  ]
  #message: "Compile Error: Type of Laminas\Code\Generator\MethodGenerator::$docBlock must be ?Laminas\Code\Generator\DocBlockGenerator (as in class Laminas\Code\Generator\AbstractMemberGenerator)"
  #code: 0
  #file: "/app/vendor/laminas/laminas-code/src/Generator/MethodGenerator.php"
  #line: 25
}
`

**Comment by edurk89** [comment]
@AlexGx , you're right. Php version 8.0.3 solves problem.
Thanks!

**Comment by Ocramius** [comment]
I couldn't find any tickets related to this: https://bugs.php.net/search.php?search_for=type&boolean=0&limit=30&order_by=&direction=DESC&cmd=display&status=Open&bug_type=All&project=All&php_os=&phpver=8.0.0&cve_id=&assign=&author_email=&bug_age=0&bug_updated=0&commented_by=

Can anyone pinpoint it on https://github.com/php/php-src/compare/php-8.0.0...php-8.0.3 ?

**Comment by Ocramius** [comment]
Closing here meanwhile, since it is evidently an upstream issue.
