### ISSUE TITLE
Zend\Code\Reflection\FileReflection crashes on Zend's module.config.php

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-code#8]
When trying to do a FileReflection on a zend module.config.php you run into a  ReflectionException when invoking FileReflection::getClasses().  Underlying problem is the tokens_get_all() function (in Zend\Code\Scanner\FileScanner::__construct) incorrectly flags the object::class constant as a T_CLASS.

---

Originally posted by @BavoJanss at https://github.com/zendframework/zend-code/issues/142

**Comment by Ocramius** [comment]
No longer needed as per #58
