### ISSUE TITLE
DocBlockGenerator output breaks when used without $longDescription 

### ISSUE THREAD

**Issue by martin-helmich** [laminas/laminas-code#80]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 4.2.1

#### Summary

`DocBlockGenerator` output formatting breaks when used without "long description".

#### Current behavior

When omitting the `$longDescription` argument, the constructur defaults to an empty string. Later checks (that assert if a `longDescription` is set) however test for `=== null` and never catch on to the fact that no description was supplied at all.

#### How to reproduce

Instantiate a `DocBlockGenerator` with empty `$longDescription` argument (2nd constructor argument):

```php
$dbg = new \Laminas\Code\Generator\DocBlockGenerator(
    "Foo",
    null,
    [new GenericTag("var", "array")]
);

echo $dbg->generate();
```

Actual output:

```
/**
 * Foo
 *
 *
 *
 * @var array
 */
```

#### Expected behavior

`$longDescription` should be able to be omitted (`=== null`) without generating comments with needlessly many LFs.

Expected output:

```
/**
 * Foo
 *
 * @var array
 */
```

#### Suggested solution

Do not initialize `$longDescription` (and probably also `$shortDescription`) with empty strings, but with `null` instead.

Alternatively, do not test for `!== null` when asserting that a long (or short) description is set, but just test for being falsy.

**Comment by Ocramius** [comment]
Closing as per #81
