### ISSUE TITLE
Zend\Code\Reflection\FileReflection getBody()

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-code#9]
When instantiating a Zend\Code\Generator\FileGenerator::fromReflection() one would expect ::generate to fully reconstruct any original file. Unfortunately Zend\Code\Reflection\FileReflection has no ::getBody method so any code outside classes is ignored.

---

Originally posted by @BavoJanss at https://github.com/zendframework/zend-code/issues/141

**Comment by Ocramius** [comment]
No longer needed as per #58
