### ISSUE TITLE
Migarting from version 3 to version 4 breaks making changes to existing classes using reflection

### ISSUE THREAD

**Issue by iganev** [laminas/laminas-code#94]
### BC Break Report

|    Q        |   A
|------------ | ------
| Version     | 3.5.1

#### Summary

Migrating from 3.5.1 to 4.4.2 seems impossible. Generation based on reflection is fundamentally broken.

#### Previous behavior

There used to be a FileReflection class in the Reflection namespace. This class no longer exists. This breaks generating classes based on existing code. FileReflection used to hold the namespace, uses and a bunch of other misc stuff. Now IN THEORY these are held in the ClassReflection, however, uses are not being parsed at all. Loading a class reflection into a class generator and then generating the code results in ALL uses getting stripped out, rendering the class source code invalid.

#### Current behavior

Judging by the documented examples and by reading the code, currently to perform code generation on existing classes I must use the ClassReflection object as a consutrctor parameter to the ClassGenerator class. This however fails to parse the use statements OUTSIDE the class and they get permanently lost. This makes generation based on existing code impossible to work in real-world cases. Reading the code of the ClassGenerator I see that both traits and uses are being bundled together... this sounds like no external uses are supported at all...

#### How to reproduce

```
<?php

require_once './vendor/autoload.php';

// REPLACE WITH A CLASS THAT YOU KNOW CONTAINS "use" STATAMENTS
$className = \Models\Table\Users::class; // REPLACE THIS WITH A PROPER EXAMPLE

$generator = \Laminas\Code\Generator\ClassGenerator::fromReflection(new \Laminas\Code\Reflection\ClassReflection($className));

$generator->addConstant('TEST', 'test');

echo $generator->generate();
```

**Comment by iganev** [comment]
There also used to be a whole bunch of Scanners... I just tried to find the CachingFileScanner to feed the right data into FileGenerator and work around the issue. That Scanner along with most of the rest also seems to be purged out of existence.

**Comment by iganev** [comment]
Cool stuff... No changelog.. but digging into the commits I found this pull request:

https://github.com/laminas/laminas-code/pull/58

**Comment by Ocramius** [comment]
Seen https://github.com/laminas/laminas-code/releases/tag/4.0.0 ?

**Comment by iganev** [comment]
Not soon enough. But eventually did. The so-called "better alternative" requires PHP >= 7.4.1 && < 7.5. So 8 is out of the question.

**Comment by Ocramius** [comment]
Yes, I and @asgrim try to do what we can during our free time: you can try and help on https://github.com/Roave/BetterReflection/issues/701 if you have an active need, and you or your employer want to chip in.

Meanwhile, the scanner component was in shambles with PHP 8 anyway, and maintaining it further was out of question.
